---
# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: samuelwalters/app:v9
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://sam-service-mongo:27017/posts
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
#Service for App
apiVersion: v1
kind: Service
metadata:
  name: sam-service-app
spec:
  selector:
    app: node
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer