---
# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_selector }}
    spec:
      containers:
        - name: {{ .Values.app_selector }}
          image: samuelwalters/app:v9
          ports:
            - containerPort: {{ .Values.app_container_port }}
          env:
            - name: {{ .Values.app_env_name }}
              value: {{ .Values.app_env_value }}
          imagePullPolicy: {{ .Values.app_image_pull_policy }}
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
#Service for App
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_service_name }}
spec:
  selector:
    app: {{ .Values.app_selector }}
  ports:
    - port: {{ .Values.app_service_port }}
      targetPort: {{ .Values.app_target_Port }}
      nodePort: {{ .Values.app_nodeport }}
  type: LoadBalancer