---
# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.app_replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_selector }}
    spec:
      containers:
        - name: {{ .Values.app_selector }}
          image: {{ .Values.samuelwalters/app:v9 }}
          ports:
            - containerPort: {{ .Values.app_container_port }}
          env:
            - name: {{ .Values.app_env_name }}
              value: {{ .Values.app_env_value }}
          imagePullPolicy: {{ .Values.app_image_pull_policy }}
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
# Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db_selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.db_selector }}
    spec:
      containers:
        - name: {{ .Values.db_selector }}
          image: {{ .Values.db_image_name }}
          ports:
            - containerPort: {{ .Values.db_container_port }}
          volumeMounts:
            - name: storage
              mountPath: /data/db