#Service for Mongodb
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db_mongo_service_name }}
spec:
  selector:
    app: {{ .Values.db_selector }}
  ports:
    - port: {{ .Values.db_container_port }}
      targetPort: {{ .Values.db_container_port }}
---
#Service for App
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_service_name }}
spec:
  selector:
    app: {{ .Values.app_selector }}
  ports:
    - port: {{ .Values.app_service_port }}
      targetPort: {{ .Values.app_target_Port }}
      nodePort: {{ .Values.app_nodeport }}
  type: LoadBalancer