# app deploy settings

app_name: eng110-node-deployment
app_replicas: 3
app_selector: node
app_image_name: samuelwalters/app:v9
app_container_port: 3000
app_env_name: DB_HOST
app_env_value: mongodb://eng110-service-mongo:27017/posts
app_image_pull_policy: Always

# app service settings

app_service_name: eng110-service-app
app_service_type: LoadBalancer
app_service_port: 80
app_target_Port: 3000
app_nodeport: 30000

# mongodb deploy settings

db_name: eng110-mongo
db_selector: mongo
db_image_name: mongo
db_container_port: 27017

# mongodb service settings

db_mongo_service_name: eng110-service-mongo
db_ports: 27017

# for ingress.yaml (which is disabled at present)

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


# for hpa.yaml (but autoscaling is also currently disabled)

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80